# Generated by Django 5.1.5 on 2025-01-15 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_category_tag_post_category_post_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "verbose_name": " post Esli ne ponimaesh uchi angl",
                "verbose_name_plural": "Posts",
            },
        ),
        migrations.RenameField(
            model_name="post",
            old_name="tags",
            new_name="tag",
        ),
    ]
